export const GTAG_ID = 'GTM-MRGJ29V';

export const GTAG_SCRIPT = `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','${GTAG_ID}');`;

export const SEGMENT_ID = 'MNlDUmtTYbs6pEQ7XDOKQ3UqkuqxFBnu';

export const SEGMENT_SCRIPT = `!function(){var analytics=window.analytics=window.analytics||[];if(!analytics.initialize)if(analytics.invoked)window.console&&console.error&&console.error("Segment snippet included twice.");else{analytics.invoked=!0;analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware"];analytics.factory=function(e){return function(){var t=Array.prototype.slice.call(arguments);t.unshift(e);analytics.push(t);return analytics}};for(var e=0;e<analytics.methods.length;e++){var key=analytics.methods[e];analytics[key]=analytics.factory(key)}analytics.load=function(key,e){var t=document.createElement("script");t.type="text/javascript";t.async=!0;t.src="https://a.joincalibrate.com/analytics.js/v1/" + key + "/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(t,n);analytics._loadOptions=e};analytics.SNIPPET_VERSION="4.13.1";}}();analytics.load("${SEGMENT_ID}");analytics.page();console.log('SEGMENT: Page Default');`;

export const COOKIESAVER_SCRIPT = `
(function(){function r(n,e,t){function i(o,u){if(!e[o]){if(!n[o]){var f="function"==typeof require&&require;if(!u&&f)return f(o,!0);if(a)return a(o,!0);var c=new Error("Cannot find module '"+o+"'");throw c.code="MODULE_NOT_FOUND",c}var s=e[o]={exports:{}};n[o][0].call(s.exports,function(r){var e=n[o][1][r];return i(e||r)},s,s.exports,r,n,e,t)}return e[o].exports}for(var a="function"==typeof require&&require,o=0;o<t.length;o++)i(t[o]);return i}return r})()({1:[function(r,n,e){"use strict";function t(r,n){return o(r)||a(r,n)||i()}function i(){throw new TypeError("Invalid attempt to destructure non-iterable instance")}function a(r,n){var e=[];var t=true;var i=false;var a=undefined;try{for(var o=r[Symbol.iterator](),u;!(t=(u=o.next()).done);t=true){e.push(u.value);if(n&&e.length===n)break}}catch(r){i=true;a=r}finally{try{if(!t&&o["return"]!=null)o["return"]()}finally{if(i)throw a}}return e}function o(r){if(Array.isArray(r))return r}(function(r,n){var e="3.2";var i=Date.now();if(!Object.entries){Object.entries=function(r){var n=Object.keys(r),e=n.length,t=new Array(e);while(e--){t[e]=[n[e],r[n[e]]]}return t}}function a(){var r="cs_test_cookie=1";var n=document.location.hostname.split(".");for(var e=n.length-1;e>=0;e--){var t=n.slice(e).join(".");document.cookie=r+";domain=."+t+";";if(document.cookie.indexOf(r)>-1){document.cookie=r.split("=")[0]+"=;domain=."+t+";expires=Thu, 01 Jan 1970 00:00:01 GMT;";return t}}return document.location.hostname}function o(r,n){var e=[n];var t=r.substring(0,r.length-n.length);if(t.length>0){var i=t.split(".");i.pop();var a=n;for(var o=i.length-1;o>=0;o--){a=i[o]+"."+a;e.push(a)}}return e}function u(r,n,e,t,i){var a=r+"="+n+";";if(e!==null){a+="expires="+e+";"}if(t!==null){a+="domain="+t+";"}if(i){a+="secure;"}a+="path=/;";document.cookie=a}var f=Date.now();var c=[];var s=document.cookie;if(!s){return}var l=a();var v=o(document.location.hostname,l);s=s.split(/; */);var h={};for(var d=0;d<s.length;d++){h[s[d].substring(0,s[d].indexOf("="))]=s[d].substring(s[d].indexOf("=")+1)}var g="_acs_";var p="_acs__acsr_";var b=[];Object.entries(h).forEach(function(r){var n=t(r,2),e=n[0],i=n[1];if(e.indexOf(g)===0){var a=true;for(var o in v){if(e===g+v[o]){a=false;break}}if(a){b.push(e);return}try{var s=JSON.parse(h[e]);if(s.c){var l=e.substring(g.length);for(var d=0,p=Object.entries(s.c);d<p.length;d++){var m=t(p[d],2),O=m[0],w=m[1];var x=parseInt(w.e,36)*1e3;if(!(O in h)&&x>f){u(O,w.v,new Date(x).toUTCString(),w.r?null:"."+l,w.s?true:false)}}}}catch(r){c.push({n:e,v:h[e],e:r})}}});b.forEach(function(r){var n=h[r];if(r.indexOf(p)===0){if(!(r.substring(p.length)in h)){u(r.substring(p.length),n,null,null,null);return}}if(r.indexOf(g)===0){if(!(r.substring(g.length)in h)){u(r.substring(g.length),n,null,l,null)}}});var m=Date.now();r.acqps={v:e,s:i,e:m,t:m-i,w:c}})(window)},{}]},{},[1]);
`;

export const ADBLOCK_TRACKING_SCRIPT = `
(function() { var baitPath = 'https://arcane-mason-322120.uc.r.appspot.com/ads-min.js'; var pixelPath = 'https://arcane-mason-322120.uc.r.appspot.com/4dchk'; if (document.location.pathname !== '/') return; var el = document.createElement('script'); el.src = baitPath; document.body.appendChild(el); var gaBlocked = false; window.addEventListener('load', function() { fetch('https://www.google-analytics.com/analytics.js', {method: 'HEAD', mode: 'no-cors'}) .catch(function() { gaBlocked = true; }) .finally(function() { var params = { ads_blocked: !document.querySelector('#GxsCRdhiJi'), gtm_blocked: !(window.google_tag_manager && window.google_tag_manager.dataLayer), ga_blocked: gaBlocked }; var cid = Math.floor((Math.random() * 1000000) + 1) + '_' + new Date().getTime(); var img = document.createElement('img'); img.style = 'width: 1; height: 1; display: none;'; img.src = pixelPath + '?client_id=' + cid + '&' + Object.keys(params).reduce(function(acc, cur) { return acc.concat(cur + '=' + params[cur]);}, []).join('&'); document.body.appendChild(img); }); }); })();
`;
